/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as NameRouteImport } from './routes/$name'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiOgRouteImport } from './routes/api/og'

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NameRoute = NameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$name': typeof NameRoute
  '/leaderboard': typeof LeaderboardRoute
  '/api/og': typeof ApiOgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$name': typeof NameRoute
  '/leaderboard': typeof LeaderboardRoute
  '/api/og': typeof ApiOgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$name': typeof NameRoute
  '/leaderboard': typeof LeaderboardRoute
  '/api/og': typeof ApiOgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$name' | '/leaderboard' | '/api/og'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$name' | '/leaderboard' | '/api/og'
  id: '__root__' | '/' | '/$name' | '/leaderboard' | '/api/og'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NameRoute: typeof NameRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ApiOgRoute: typeof ApiOgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$name': {
      id: '/$name'
      path: '/$name'
      fullPath: '/$name'
      preLoaderRoute: typeof NameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NameRoute: NameRoute,
  LeaderboardRoute: LeaderboardRoute,
  ApiOgRoute: ApiOgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
